project_id = "growup"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[auth]
site_url = "http://localhost:4200"
additional_redirect_urls = ["http://localhost:4200"]

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"

[analytics]
enabled = false
